# Promox workflow

on:
  workflow_dispatch:
  
jobs:
  my_job:
    name: My Promox runner 
    runs-on: self-hosted

    steps:
    -  name: Checkout project
    -  uses: actions/checkout@v4

    -  name: Running Pytest
    
    -  run: pytest
        
    
